# Hugo build configuration for Netlify 
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  command = "git submodule update -f --init && cd userguide && npm install postcss-cli && hugo --themesDir ../.."

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.58.3"
